import {
  useEffect,
  useId,
  useMemo,
  useState,
  type CSSProperties,
  type FocusEvent,
} from "react";
import Band from "@/components/primitives/Band";
import { sectionIndex } from "@/lib/sections";
import { useLocale } from "@/lib/i18n";
import type { Accent, SkillGroup, SkillNode } from "@/content/types";

/* ============================================================================
 * The skills mindmap.
 *
 * Two things shape every decision in this file.
 *
 * 1. The page is prerendered, so the geometry has to come out bit-for-bit
 *    identical in Node and in every browser or hydration fails. That rules out
 *    measuring the DOM, and — see `sinTurns` — it rules out Math.sin/cos too.
 *
 * 2. An SVG <g> cannot hold focus. The nodes are therefore real HTML buttons
 *    laid over the drawing, the drawing itself is decorative, and the same
 *    buttons reflow into a grouped chip list below `md`, where a graph this
 *    dense would be unusable. One set of controls, two presentations, so the
 *    small screen can never fall behind the large one.
 * ========================================================================== */

type Target = `node:${string}` | `group:${string}`;

/** `field` paints light — lines, glows, borders. `ink` is the same hue made
 *  safe as text: raw violet (3.3:1) and raw azure (4.0:1) miss AA on the void,
 *  so their letters are lifted toward cream. Ember and rust already clear it. */
const TONE: Record<Accent, { field: string; ink: string }> = {
  ember: { field: "var(--ember)", ink: "var(--ember)" },
  rust: { field: "var(--rust)", ink: "var(--rust)" },
  violet: {
    field: "var(--violet)",
    ink: "color-mix(in oklch, var(--violet) 58%, var(--cream))",
  },
  azure: {
    field: "var(--azure)",
    ink: "color-mix(in oklch, var(--azure) 58%, var(--cream))",
  },
};

/* ---------------------------------------------------------------------------
 * Deterministic trigonometry
 * -------------------------------------------------------------------------*/

/* ECMAScript does not specify the results of Math.sin and Math.cos beyond
   "implementation-approximated", and the suite runs against Chromium and
   WebKit while the markup is generated by Node. A one-ULP disagreement is
   enough to change a rounded coordinate and produce a hydration mismatch, so
   the angles are evaluated here instead: argument reduction to a quarter turn
   plus a Taylor series in nothing but +, - and *, all of which IEEE-754 does
   pin down exactly. Error is below 1e-9 — six orders of magnitude finer than
   the two decimals that survive rounding. */
const QUARTER = 1.5707963267948966;

function sinQuarter(r: number): number {
  const a = QUARTER * r;
  const s = a * a;
  return (
    a *
    (1 +
      s *
        (-1 / 6 +
          s * (1 / 120 + s * (-1 / 5040 + s * (1 / 362880 + s * (-1 / 39916800))))))
  );
}

function cosQuarter(r: number): number {
  const a = QUARTER * r;
  const s = a * a;
  return (
    1 +
    s * (-1 / 2 + s * (1 / 24 + s * (-1 / 720 + s * (1 / 40320 + s * (-1 / 3628800)))))
  );
}

/** Angles are in turns, so a quarter is 0.25 and the reduction is exact. */
function sinTurns(t: number): number {
  const f = (t - Math.floor(t)) * 4;
  const q = Math.floor(f);
  const r = f - q;
  if (q === 0) return sinQuarter(r);
  if (q === 1) return cosQuarter(r);
  if (q === 2) return -sinQuarter(r);
  return -cosQuarter(r);
}

function cosTurns(t: number): number {
  return sinTurns(t + 0.25);
}

function round(value: number): number {
  return Math.round(value * 100) / 100;
}

/* ---------------------------------------------------------------------------
 * Geometry
 * -------------------------------------------------------------------------*/

/** Everything is laid out in a 0–100 square that the SVG stretches to fill
 *  (`preserveAspectRatio="none"`), which is what lets the same coordinates be
 *  both SVG units and CSS percentages at any container shape. */
const GEOM = {
  /* Rings sized so the whole composition, glow included, clears the edges at
     32 nodes. They were 29/27 and 18/22 when the map held 24: a fan spreads
     wider with more members, and the outermost chips ended up pinned flat
     against the boundary with their glow hanging over it. */
  hubRx: 26,
  hubRy: 24,
  nodeRx: 17,
  nodeRy: 18,
  /** Radius of the soft field painted under a hub. An SVG root clips at its own
   *  viewport, so this can never exceed the hub's distance to the canvas edge:
   *  a larger value does not paint a wider glow, it paints a round one with a
   *  straight bite taken out of it. 26 + 24 = 50 puts the rim exactly on the
   *  edge, where the gradient has already fallen to zero. Enforced below rather
   *  than trusted, so the constraint travels if the ring ever moves. */
  glow: 24,
  /** Turns of arc a group's nodes fan across, centred on the direction away
   *  from the middle. The inward gap it leaves is where the cross-group curves
   *  run. */
  spread: 0.66,
  /** Odd-indexed nodes sit on a tighter ring, so neighbours in the fan are
   *  separated by radius as well as by angle. */
  innerRing: 0.72,
  iterations: 160,
  gapX: 2.2,
  gapY: 1.8,
  /** Fraction of the way from an edge's midpoint to the centre of the canvas
   *  that its control point sits — the pull that turns a chord into a curve. */
  bow: 0.42,
} as const;

/* Chip footprints are estimated from label length against the tightest
   container the graph is ever drawn in (~672 x 480 at the md breakpoint), so
   the separation pass below is always solving the worst case and every wider
   viewport only adds air. Deliberately generous: a label is measured, never
   guessed, only by the browser, and this has to hold for both locales.

   The coefficients are an upper bound on every label in both locales as the
   browser actually draws them, checked at 768 / 1024 / 1440 / 1920. The old
   pair was a fit, not a bound — it under-measured a short all-caps label like
   CPQ by 3px a side, which is precisely the error that ends up on the edge. */
const REF_W = 672;
const REF_H = 480;

function chipBox(label: string): { hx: number; hy: number } {
  return {
    hx: ((38 + label.length * 7.2) / 2 / REF_W) * 100,
    hy: (31 / 2 / REF_H) * 100,
  };
}

function hubBox(label: string): { hx: number; hy: number } {
  return {
    hx: ((26 + label.length * 8.2) / 2 / REF_W) * 100,
    hy: (29 / 2 / REF_H) * 100,
  };
}

/* A node paints well outside its own border box, and none of it is in
   getBoundingClientRect: the selected state's `0 0 34px -6px` shadow reaches
   blur / 2 + spread = 11px past the edge, and `scale(1.06)` then carries the
   whole painting — shadow included — a further 6% of its own half-size
   outward. Fitting the boxes inside the stage therefore fits nothing; the glow
   is what the eye sees against the edge. Twelve, for the eleven plus the
   antialiased tail, reserved in the same reference frame as the footprints. */
const PAINT_PX = 12;
const SELECTED_SCALE = 1.06;
const PAD_X = (PAINT_PX / REF_W) * 100;
const PAD_Y = (PAINT_PX / REF_H) * 100;

interface HubPoint {
  id: string;
  label: string;
  accent: Accent;
  angle: number;
  x: number;
  y: number;
  hx: number;
  hy: number;
}

interface NodePoint {
  node: SkillNode;
  group: HubPoint;
  x: number;
  y: number;
  homeX: number;
  homeY: number;
  hx: number;
  hy: number;
  /** Half-extent of everything the node paints, not of its box. This is what
   *  the canvas edge is measured against. */
  reachX: number;
  reachY: number;
}

interface MapNode {
  id: string;
  label: string;
  note?: string;
  group: string;
  groupLabel: string;
  accent: Accent;
  x: number;
  y: number;
}

interface MapHub {
  id: string;
  label: string;
  accent: Accent;
  x: number;
  y: number;
}

interface MapSpoke {
  node: string;
  group: string;
  accent: Accent;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

interface MapEdge {
  id: string;
  a: string;
  b: string;
  cross: boolean;
  accentA: Accent;
  accentB: Accent;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  d: string;
}

interface SkillMap {
  hubs: MapHub[];
  clusters: { hub: MapHub; nodes: MapNode[] }[];
  byId: Map<string, MapNode>;
  spokes: MapSpoke[];
  edges: MapEdge[];
  neighbours: Map<string, string[]>;
  glow: { rx: number; ry: number };
}

/** Pure: the same content always yields the same map, on the server and in the
 *  browser, with no DOM involved. */
function buildMap(
  groups: readonly SkillGroup[],
  nodes: readonly SkillNode[],
): SkillMap {
  const hubs: HubPoint[] = groups.map((group, index) => {
    /* Start at the top and step clockwise, so the groups appear around the
       canvas in the order they are written in the content file. */
    const angle = 0.75 + index / Math.max(1, groups.length);
    return {
      id: group.id,
      label: group.label,
      accent: group.accent,
      angle,
      x: 50 + GEOM.hubRx * cosTurns(angle),
      y: 50 + GEOM.hubRy * sinTurns(angle),
      ...hubBox(group.label),
    };
  });

  const points: NodePoint[] = [];
  for (const hub of hubs) {
    const members = nodes.filter((node) => node.group === hub.id);
    members.forEach((node, index) => {
      const offset = members.length === 1 ? 0 : index / (members.length - 1) - 0.5;
      const angle = hub.angle + GEOM.spread * offset;
      const ring = index % 2 === 0 ? 1 : GEOM.innerRing;
      const x = hub.x + GEOM.nodeRx * ring * cosTurns(angle);
      const y = hub.y + GEOM.nodeRy * ring * sinTurns(angle);
      const box = chipBox(node.label);
      points.push({
        node,
        group: hub,
        x,
        y,
        homeX: x,
        homeY: y,
        ...box,
        reachX: (box.hx + PAD_X) * SELECTED_SCALE,
        reachY: (box.hy + PAD_Y) * SELECTED_SCALE,
      });
    });
  }

  relax(points, hubs);

  const clusters = hubs.map((hub) => ({
    hub: {
      id: hub.id,
      label: hub.label,
      accent: hub.accent,
      x: round(hub.x),
      y: round(hub.y),
    },
    nodes: points
      .filter((point) => point.group.id === hub.id)
      .map<MapNode>((point) => ({
        id: point.node.id,
        label: point.node.label,
        note: point.node.note,
        group: hub.id,
        groupLabel: hub.label,
        accent: hub.accent,
        x: round(point.x),
        y: round(point.y),
      })),
  }));

  const byId = new Map<string, MapNode>();
  for (const cluster of clusters) {
    for (const node of cluster.nodes) byId.set(node.id, node);
  }

  const spokes: MapSpoke[] = [];
  for (const cluster of clusters) {
    for (const node of cluster.nodes) {
      spokes.push({
        node: node.id,
        group: cluster.hub.id,
        accent: cluster.hub.accent,
        x1: cluster.hub.x,
        y1: cluster.hub.y,
        x2: node.x,
        y2: node.y,
      });
    }
  }

  /* `related` is written from one side only and is not always reciprocated, so
     the pairs are normalised and de-duplicated rather than trusted. An id that
     no longer resolves is dropped: content is edited by hand and a stale
     reference should cost a line, not the section. */
  const edges: MapEdge[] = [];
  const seen = new Set<string>();
  const neighbours = new Map<string, string[]>();

  for (const node of nodes) {
    for (const targetId of node.related ?? []) {
      const from = byId.get(node.id);
      const to = byId.get(targetId);
      if (!from || !to || from.id === to.id) continue;

      const [a, b] = from.id < to.id ? [from, to] : [to, from];
      const id = `${a.id}--${b.id}`;
      if (seen.has(id)) continue;
      seen.add(id);

      neighbours.set(a.id, [...(neighbours.get(a.id) ?? []), b.id]);
      neighbours.set(b.id, [...(neighbours.get(b.id) ?? []), a.id]);

      /* Quadratic, with the control point pulled toward the middle of the
         canvas. The fans leave that middle empty, so the curves bundle through
         it instead of cutting across the labels a straight chord would hit. */
      const midX = (a.x + b.x) / 2;
      const midY = (a.y + b.y) / 2;
      const cx = round(midX + (50 - midX) * GEOM.bow);
      const cy = round(midY + (50 - midY) * GEOM.bow);

      edges.push({
        id,
        a: a.id,
        b: b.id,
        cross: a.group !== b.group,
        accentA: a.accent,
        accentB: b.accent,
        x1: a.x,
        y1: a.y,
        x2: b.x,
        y2: b.y,
        d: `M${a.x} ${a.y}Q${cx} ${cy} ${b.x} ${b.y}`,
      });
    }
  }

  const hubPoints = clusters.map((cluster) => cluster.hub);

  return {
    hubs: hubPoints,
    clusters,
    byId,
    spokes,
    edges,
    neighbours,
    /* Taken from the hub that sits nearest an edge rather than from GEOM alone,
       so the four stay identical and the fit survives a different number of
       groups putting the hubs somewhere other than the four cardinal points. */
    glow: {
      rx: Math.min(GEOM.glow, ...hubPoints.map((hub) => Math.min(hub.x, 100 - hub.x))),
      ry: Math.min(GEOM.glow, ...hubPoints.map((hub) => Math.min(hub.y, 100 - hub.y))),
    },
  };
}

/** Pushes overlapping chips apart while a weak spring holds each one near the
 *  ring position it was born at, so the four fans stay legible as fans. The
 *  forces are continuous — magnitude falls to zero exactly where the boxes stop
 *  touching — which keeps the result stable rather than letting a hair's-width
 *  difference flip a branch and move a node across the canvas. */
function relax(points: NodePoint[], hubs: HubPoint[]): void {
  for (let pass = 0; pass < GEOM.iterations; pass++) {
    for (let i = 0; i < points.length; i++) {
      const a = points[i];
      if (!a) continue;

      for (let j = i + 1; j < points.length; j++) {
        const b = points[j];
        if (!b) continue;
        const dx = b.x - a.x;
        const dy = b.y - a.y;
        const ox = Math.max(0, a.hx + b.hx + GEOM.gapX - Math.abs(dx));
        const oy = Math.max(0, a.hy + b.hy + GEOM.gapY - Math.abs(dy));
        const push = Math.min(ox, oy);
        if (push === 0) continue;

        /* Split across both axes in inverse proportion to how deep the boxes
           are on each, which resolves along the shallower one without the jump
           a hard "pick an axis" test would introduce. */
        const total = ox + oy;
        const mx = ((push * oy) / total) * (dx >= 0 ? 0.5 : -0.5);
        const my = ((push * ox) / total) * (dy >= 0 ? 0.5 : -0.5);
        a.x -= mx;
        a.y -= my;
        b.x += mx;
        b.y += my;
      }

      for (const hub of hubs) {
        const dx = hub.x - a.x;
        const dy = hub.y - a.y;
        const ox = Math.max(0, a.hx + hub.hx + GEOM.gapX - Math.abs(dx));
        const oy = Math.max(0, a.hy + hub.hy + GEOM.gapY - Math.abs(dy));
        const push = Math.min(ox, oy);
        if (push === 0) continue;
        const total = ox + oy;
        a.x -= ((push * oy) / total) * (dx >= 0 ? 1 : -1);
        a.y -= ((push * ox) / total) * (dy >= 0 ? 1 : -1);
      }
    }

    for (const point of points) {
      point.x += (point.homeX - point.x) * 0.03;
      point.y += (point.homeY - point.y) * 0.03;
      /* Against the painted half-extent, not the box. The old bound was the
         box plus a flat 1% of the canvas — under 5px of the short side — so a
         node could satisfy it and still hang its glow over the edge. */
      point.x = Math.min(100 - point.reachX, Math.max(point.reachX, point.x));
      point.y = Math.min(100 - point.reachY, Math.max(point.reachY, point.y));
    }
  }
}

/* ---------------------------------------------------------------------------
 * Highlighting
 * -------------------------------------------------------------------------*/

interface Lit {
  on: boolean;
  nodes: Set<string>;
  hubs: Set<string>;
  spokes: Set<string>;
  edges: Set<string>;
}

function resolve(map: SkillMap, target: Target | null): Lit {
  const lit: Lit = {
    on: target !== null,
    nodes: new Set(),
    hubs: new Set(),
    spokes: new Set(),
    edges: new Set(),
  };
  if (!target) return lit;

  if (target.startsWith("group:")) {
    const groupId = target.slice(6);
    lit.hubs.add(groupId);
    for (const cluster of map.clusters) {
      if (cluster.hub.id !== groupId) continue;
      for (const node of cluster.nodes) {
        lit.nodes.add(node.id);
        lit.spokes.add(node.id);
      }
    }
    for (const edge of map.edges) {
      if (lit.nodes.has(edge.a) || lit.nodes.has(edge.b)) lit.edges.add(edge.id);
    }
    return lit;
  }

  const nodeId = target.slice(5);
  const self = map.byId.get(nodeId);
  if (!self) return lit;

  lit.nodes.add(nodeId);
  lit.hubs.add(self.group);
  lit.spokes.add(nodeId);
  for (const other of map.neighbours.get(nodeId) ?? []) lit.nodes.add(other);
  for (const edge of map.edges) {
    if (edge.a === nodeId || edge.b === nodeId) lit.edges.add(edge.id);
  }
  return lit;
}

function stateOf(lit: Lit, isLit: boolean): "rest" | "lit" | "dim" {
  if (!lit.on) return "rest";
  return isLit ? "lit" : "dim";
}

/* ---------------------------------------------------------------------------
 * Styles
 * -------------------------------------------------------------------------*/

/* Scoped to `halo-sk-*` and kept out of the global sheet: none of it is
   reusable, and the whole point of the block is one element switching between
   two entirely different layouts at `md`.

   The dimmed state is carried by border, background, glow and scale — text
   never drops below `--haze` at 0.8, which is 5.4:1 on the void. Fading labels
   to the point where the effect reads well would put them under 4.5:1, and a
   graph that is only usable for the currently selected item is not a graph. */
const MAP_CSS = `
.halo-sk-legend {
  display: none;
}

.halo-sk-field {
  display: grid;
  gap: 2.25rem;
}

.halo-sk-canvas {
  display: none;
}

.halo-sk-hub {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  margin: 0 0 0.875rem;
  border: 1px solid var(--ac-line);
  background: var(--void-deep);
  padding: 0.3125rem 0.75rem;
  font-family: var(--font-mono);
  font-size: var(--text-meta);
  font-weight: 500;
  letter-spacing: 0.14em;
  line-height: 1.4;
  text-transform: uppercase;
  white-space: nowrap;
  color: var(--ac-ink);
  transition:
    border-color var(--dur-state) var(--ease-out),
    box-shadow var(--dur-state) var(--ease-out),
    opacity var(--dur-state) var(--ease-out);
}
.halo-sk-hub[data-state="lit"] {
  border-color: var(--ac);
  box-shadow: 0 0 26px -6px var(--ac);
}
.halo-sk-hub[data-state="dim"] {
  opacity: 0.55;
}

.halo-sk-nodes {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.halo-sk-node {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  border: 1px solid var(--hairline-strong);
  /* Opaque, always: the chips sit over the drawing, and a translucent one
     would put gradient behind live text. */
  background: var(--void);
  padding: 0.375rem 0.625rem;
  font-family: var(--font-sans);
  font-size: 0.8125rem;
  line-height: 1.25;
  white-space: nowrap;
  color: var(--cream);
  cursor: pointer;
  transition:
    color var(--dur-state) var(--ease-out),
    opacity var(--dur-state) var(--ease-out),
    border-color var(--dur-state) var(--ease-out),
    background-color var(--dur-state) var(--ease-out),
    box-shadow var(--dur-state) var(--ease-out),
    transform var(--dur-state) var(--ease-settle);
}
.halo-sk-node[data-state="dim"] {
  border-color: var(--hairline);
  color: var(--haze);
  opacity: 0.8;
}
.halo-sk-node[data-state="lit"] {
  border-color: var(--ac);
  background: var(--surface-raised);
  box-shadow: 0 0 24px -8px var(--ac);
}
/* Selection is never colour alone: a ring, a lift and a larger marker carry it
   as well, and aria-pressed carries it to anything that cannot see. */
.halo-sk-node[aria-pressed="true"] {
  border-color: var(--ac);
  background: var(--surface-raised);
  box-shadow:
    0 0 0 1px var(--ac),
    0 0 34px -6px var(--ac);
  transform: scale(1.06);
}

.halo-sk-mark {
  flex: none;
  width: 0.375rem;
  height: 0.375rem;
  border-radius: 50%;
  background: var(--ac);
  transition:
    transform var(--dur-state) var(--ease-settle),
    box-shadow var(--dur-state) var(--ease-out);
}
.halo-sk-node[aria-pressed="true"] .halo-sk-mark {
  transform: scale(1.5);
  box-shadow: 0 0 10px 1px var(--ac);
}

.halo-sk-detail {
  margin-top: 2.5rem;
  border-left: 2px solid var(--ac-line, var(--hairline-strong));
  padding: 0.25rem 0 0.25rem 1.25rem;
  min-height: 7.5rem;
}

.halo-sk-related {
  display: flex;
  flex-wrap: wrap;
  gap: 0.375rem 0.5rem;
  margin-top: 1rem;
}
.halo-sk-related > li {
  display: inline-flex;
  align-items: center;
  gap: 0.4375rem;
  border: 1px solid var(--hairline);
  padding: 0.1875rem 0.5rem;
  font-family: var(--font-mono);
  font-size: var(--text-meta);
  letter-spacing: 0.08em;
  color: var(--haze);
}

@media (min-width: 48rem) {
  .halo-sk-legend {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-bottom: 1.75rem;
  }

  /* Taller than the 30–45rem this held at 24 nodes. Thirty-two chips in the
     same box only fit by crowding the middle and leaning on the edges, and the
     graph is a full-width feature — height is the cheap dimension here. Still
     under a viewport at every size, so it is a section and not a page. */
  .halo-sk-field {
    display: block;
    position: relative;
    height: clamp(33rem, 54vw, 48rem);
  }

  .halo-sk-canvas {
    display: block;
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
  }

  /* The four group wrappers collapse to nothing and everything inside them is
     positioned against the field, so the DOM can stay grouped — which is what
     assistive technology and the small-screen list both read — while the
     picture is free. */
  .halo-sk-hub,
  .halo-sk-slot {
    position: absolute;
    transform: translate(-50%, -50%);
    z-index: 1;
  }
  .halo-sk-hub {
    margin: 0;
    z-index: 2;
  }
  .halo-sk-slot[data-state="lit"],
  .halo-sk-slot[data-state="sel"] {
    z-index: 3;
  }

  .halo-sk-nodes {
    display: block;
  }

  .halo-sk-node {
    font-size: 0.75rem;
  }

  .halo-sk-detail {
    margin-top: 2rem;
    min-height: 6.5rem;
  }
}

@media (min-width: 64rem) {
  .halo-sk-node {
    font-size: 0.8125rem;
  }
}

.halo-sk-edge,
.halo-sk-spoke,
.halo-sk-glow {
  transition:
    opacity var(--dur-state) var(--ease-out),
    stroke-width var(--dur-state) var(--ease-out);
}

.halo-sk-spoke {
  opacity: 0.3;
}
.halo-sk-spoke[data-state="lit"] {
  opacity: 0.9;
}
.halo-sk-spoke[data-state="dim"] {
  opacity: 0.07;
}

.halo-sk-edge {
  opacity: 0.5;
}
.halo-sk-edge[data-state="lit"] {
  opacity: 1;
  stroke-width: 2.25;
}
.halo-sk-edge[data-state="dim"] {
  opacity: 0.07;
}

.halo-sk-glow {
  opacity: 0.5;
}
.halo-sk-glow[data-state="lit"] {
  opacity: 1;
}
.halo-sk-glow[data-state="dim"] {
  opacity: 0.14;
}
`;

/* ---------------------------------------------------------------------------
 * Component
 * -------------------------------------------------------------------------*/

export default function Skills() {
  const { t } = useLocale();
  const { label, heading, intro, hint, groups, nodes } = t.skills;

  /* Colons are legal in a fragment but not worth betting `url(#…)` on. */
  const uid = useId().replace(/:/g, "");
  const map = useMemo(() => buildMap(groups, nodes), [groups, nodes]);

  const [selected, setSelected] = useState<Target | null>(null);
  const [hovered, setHovered] = useState<Target | null>(null);
  const [focused, setFocused] = useState<Target | null>(null);

  /* Pointer beats keyboard beats what is committed: a preview shows the same
     highlight without disturbing the selection, exactly as leaving the element
     restores it. */
  const active = hovered ?? focused ?? selected;
  const lit = useMemo(() => resolve(map, active), [map, active]);

  function toggle(target: Target) {
    setSelected((current) => (current === target ? null : target));
  }

  /* Escape is bound to the document rather than to the map, because Safari does
     not move focus to a button when you click it: after a mouse selection the
     keystroke lands on <body>, and a handler scoped to this subtree would never
     see it. Registered only while something is selected, so it is inert the
     rest of the time. */
  useEffect(() => {
    if (selected === null) return;
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") setSelected(null);
    }
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [selected]);

  /* A pointer press focuses the button before it clicks it. Committing on any
     focus would make the click that follows read as a second press and undo
     itself, so only a keyboard focus previews. */
  function previewOnFocus(target: Target) {
    return (event: FocusEvent<HTMLButtonElement>) => {
      if (event.currentTarget.matches(":focus-visible")) setFocused(target);
    };
  }

  const detail = selected;
  const detailNode = detail?.startsWith("node:")
    ? map.byId.get(detail.slice(5))
    : undefined;
  const detailHub = detail?.startsWith("group:")
    ? map.hubs.find((hub) => hub.id === detail.slice(6))
    : undefined;
  const detailTone = detailNode
    ? TONE[detailNode.accent]
    : detailHub
      ? TONE[detailHub.accent]
      : undefined;
  const detailRelated = detailNode
    ? (map.neighbours.get(detailNode.id) ?? [])
        .map((id) => map.byId.get(id))
        .filter((node): node is MapNode => node !== undefined)
    : [];
  const detailMembers = detailHub
    ? (map.clusters.find((cluster) => cluster.hub.id === detailHub.id)?.nodes ?? [])
    : [];

  return (
    <Band
      id="skills"
      index={sectionIndex("skills")}
      label={label}
      heading={heading}
      intro={intro}
    >
      <style>{MAP_CSS}</style>

      <div data-rise>
        <ul className="halo-sk-legend" role="list">
          {map.hubs.map((hub) => {
            const tone = TONE[hub.accent];
            const target: Target = `group:${hub.id}`;
            return (
              <li key={hub.id}>
                <button
                  type="button"
                  className="halo-sk-node"
                  style={{ "--ac": tone.field } as CSSProperties}
                  data-state={stateOf(lit, lit.hubs.has(hub.id))}
                  aria-pressed={selected === target}
                  onClick={() => toggle(target)}
                  onPointerEnter={() => setHovered(target)}
                  onPointerLeave={() => setHovered(null)}
                  onFocus={previewOnFocus(target)}
                  onBlur={() => setFocused(null)}
                >
                  <span className="halo-sk-mark" />
                  {hub.label}
                </button>
              </li>
            );
          })}
        </ul>

        <div className="halo-sk-field">
          {/* Decorative by construction: every line here restates a relation
              that the buttons and the text equivalent below already carry. */}
          <svg
            className="halo-sk-canvas"
            viewBox="0 0 100 100"
            preserveAspectRatio="none"
            aria-hidden="true"
            focusable="false"
          >
            <defs>
              {map.hubs.map((hub) => (
                <radialGradient key={hub.id} id={`${uid}-glow-${hub.id}`}>
                  <stop
                    offset="0%"
                    stopColor={TONE[hub.accent].field}
                    stopOpacity="0.3"
                  />
                  <stop
                    offset="100%"
                    stopColor={TONE[hub.accent].field}
                    stopOpacity="0"
                  />
                </radialGradient>
              ))}
              {/* Cross-group edges only: those are the ones drawn in two
                  colours, so a same-group edge would define a gradient from a
                  hue to itself and never reference it. */}
              {map.edges
                .filter((edge) => edge.cross)
                .map((edge) => (
                  <linearGradient
                    key={edge.id}
                    id={`${uid}-edge-${edge.id}`}
                    gradientUnits="userSpaceOnUse"
                    x1={edge.x1}
                    y1={edge.y1}
                    x2={edge.x2}
                    y2={edge.y2}
                  >
                    <stop offset="0%" stopColor={TONE[edge.accentA].field} />
                    <stop offset="100%" stopColor={TONE[edge.accentB].field} />
                  </linearGradient>
                ))}
            </defs>

            {map.hubs.map((hub) => (
              <ellipse
                key={hub.id}
                className="halo-sk-glow"
                data-state={stateOf(lit, lit.hubs.has(hub.id))}
                cx={hub.x}
                cy={hub.y}
                rx={map.glow.rx}
                ry={map.glow.ry}
                fill={`url(#${uid}-glow-${hub.id})`}
              />
            ))}

            {map.spokes.map((spoke) => (
              <line
                key={spoke.node}
                className="halo-sk-spoke"
                data-state={stateOf(lit, lit.spokes.has(spoke.node))}
                x1={spoke.x1}
                y1={spoke.y1}
                x2={spoke.x2}
                y2={spoke.y2}
                stroke={TONE[spoke.accent].field}
                strokeWidth="1"
                vectorEffect="non-scaling-stroke"
              />
            ))}

            {map.edges.map((edge) => (
              <path
                key={edge.id}
                className="halo-sk-edge"
                data-state={stateOf(lit, lit.edges.has(edge.id))}
                d={edge.d}
                fill="none"
                stroke={
                  edge.cross ? `url(#${uid}-edge-${edge.id})` : TONE[edge.accentA].field
                }
                strokeWidth={edge.cross ? 1.5 : 1}
                strokeDasharray={edge.cross ? undefined : "2 3"}
                strokeLinecap="round"
                vectorEffect="non-scaling-stroke"
              />
            ))}
          </svg>

          {map.clusters.map((cluster) => {
            const tone = TONE[cluster.hub.accent];
            return (
              <div
                key={cluster.hub.id}
                style={
                  {
                    "--ac": tone.field,
                    "--ac-ink": tone.ink,
                    "--ac-line": `color-mix(in oklch, ${tone.field} 45%, transparent)`,
                  } as CSSProperties
                }
              >
                <h3
                  className="halo-sk-hub"
                  data-state={stateOf(lit, lit.hubs.has(cluster.hub.id))}
                  style={{ left: `${cluster.hub.x}%`, top: `${cluster.hub.y}%` }}
                >
                  {cluster.hub.label}
                </h3>

                <ul className="halo-sk-nodes" role="list">
                  {cluster.nodes.map((node) => {
                    const target: Target = `node:${node.id}`;
                    const state = stateOf(lit, lit.nodes.has(node.id));
                    return (
                      <li
                        key={node.id}
                        className="halo-sk-slot"
                        data-state={selected === target ? "sel" : state}
                        style={{ left: `${node.x}%`, top: `${node.y}%` }}
                      >
                        <button
                          type="button"
                          className="halo-sk-node"
                          data-state={state}
                          aria-pressed={selected === target}
                          onClick={() => toggle(target)}
                          onPointerEnter={() => setHovered(target)}
                          onPointerLeave={() => setHovered(null)}
                          onFocus={previewOnFocus(target)}
                          onBlur={() => setFocused(null)}
                        >
                          <span className="halo-sk-mark" />
                          {node.label}
                        </button>
                      </li>
                    );
                  })}
                </ul>
              </div>
            );
          })}
        </div>

        {/* Resting state is the hint, so the guidance occupies the space the
            detail will need rather than a line of its own that goes stale. */}
        <div
          className="halo-sk-detail"
          aria-live="polite"
          style={
            detailTone
              ? ({
                  "--ac-line": `color-mix(in oklch, ${detailTone.field} 55%, transparent)`,
                } as CSSProperties)
              : undefined
          }
        >
          {detailNode ? (
            <>
              <p className="meta" style={{ color: detailTone?.ink }}>
                {detailNode.groupLabel}
              </p>
              <p className="text-lead mt-2 text-cream">{detailNode.label}</p>
              {detailNode.note ? (
                <p className="measure mt-3 text-body text-haze">{detailNode.note}</p>
              ) : null}
              {detailRelated.length > 0 ? (
                <ul className="halo-sk-related" role="list">
                  {detailRelated.map((related) => (
                    <li
                      key={related.id}
                      style={{ "--ac": TONE[related.accent].field } as CSSProperties}
                    >
                      <span className="halo-sk-mark" />
                      {related.label}
                    </li>
                  ))}
                </ul>
              ) : null}
            </>
          ) : detailHub ? (
            <>
              <p className="meta" style={{ color: detailTone?.ink }}>
                {detailHub.label}
              </p>
              <ul className="halo-sk-related" role="list">
                {detailMembers.map((member) => (
                  <li
                    key={member.id}
                    style={{ "--ac": TONE[member.accent].field } as CSSProperties}
                  >
                    <span className="halo-sk-mark" />
                    {member.label}
                  </li>
                ))}
              </ul>
            </>
          ) : (
            <p className="meta">{hint}</p>
          )}
        </div>
      </div>

      {/* The drawing is decorative and the buttons carry only their own names,
          so this is where the map exists as prose: every group, every node, its
          note, and the nodes it meets. It is rendered at every breakpoint, so
          there is no size at which the text equivalent is thinner than the
          picture. */}
      <div className="sr-only">
        <ul role="list">
          {map.clusters.map((cluster) => (
            <li key={cluster.hub.id}>
              {cluster.hub.label}
              <ul role="list">
                {cluster.nodes.map((node) => {
                  const related = (map.neighbours.get(node.id) ?? [])
                    .map((id) => map.byId.get(id))
                    .filter((other): other is MapNode => other !== undefined);
                  return (
                    <li key={node.id}>
                      {node.label}
                      {node.note ? <p>{node.note}</p> : null}
                      {related.length > 0 ? (
                        <ul role="list">
                          {related.map((other) => (
                            <li key={other.id}>
                              {other.label} — {other.groupLabel}
                            </li>
                          ))}
                        </ul>
                      ) : null}
                    </li>
                  );
                })}
              </ul>
            </li>
          ))}
        </ul>
      </div>
    </Band>
  );
}
